program: src/mlops_project/train.py
method: bayes # Bayes intelligently searches the hyperparameter space instead of blindly trying every combination
project: skin-lesion-cancer-classification
name: efficientnet-sweep
command:
  - uv
  - run
  - ${program}
  - model=efficientnet
  - ${args_no_hyphens}

metric:
  name: val_loss
  goal: minimize

parameters:
  model.lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  model.model_size:
    values: ["b0", "b1", "b2", "b3", "b4"]
  training.max_epochs:
    distribution: int_uniform
    min: 15
    max: 40
  data.batch_size:
    values: [16, 32, 64]
  model.freeze_backbone:
    values: [true, false]

early_terminate:
  type: hyperband
  min_iter: 3
