_wandb:
    value:
        cli_version: 0.23.1
        e:
            42vssbmv3xsp2cm45nnwrklg4m01k4v9:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1081101176832"
                        used: "18404130816"
                email: marwansummakieh97@gmail.com
                executable: /workspaces/dtu-vibe-ops-02476/.venv/bin/python3
                git:
                    commit: 2ba190e25585f506cb3903a7d53bb15ab5342a62
                    remote: https://github.com/Aryan-Mi/dtu-vibe-ops-02476.git
                host: de21f7ae7f5d
                memory:
                    total: "8218951680"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31
                program: <python with no main file>
                python: CPython 3.12.11
                root: /workspaces/dtu-vibe-ops-02476
                startedAt: "2026-01-11T13:06:28.503630Z"
                writerId: 42vssbmv3xsp2cm45nnwrklg4m01k4v9
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
            "4": 3.12.11
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
